# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24df569c7e348c1fb7a62c9085af5d89a2f517f5f80001b962060bedff39297f11fd0eecd7f593b48619d530434531030c26e6bc55193d68889aa6efecb3e5be

test:
  secret_key_base: ee1370e9fdee20e4742331d80cdf96e5e9e6c8a0e9fac9b56c0200060c15a8a968106f59da484f882263d00cc87232757357c40b374d4eef1c95498fe2d3ea5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
