Chore.create({title: 'Vaccuum living areas', frequency: 7, last_done: Date.today - 7})
Chore.create({title: 'Vaccuum bedroom', frequency: 7, last_done: Date.today - 7})
Chore.create({title: 'Vaccuum spare room', frequency: 14, last_done: Date.today - 7})
Chore.create({title: 'Change sheets', frequency: 14, last_done: Date.today - 7})
Chore.create({title: 'Mop floors', frequency: 30, last_done: Date.today - 7})
Chore.create({title: 'Kitchen surfaces', frequency: 7, last_done: Date.today - 7})
Chore.create({title: 'Bathroom surfaces', frequency: 7, last_done: Date.today - 7})
Chore.create({title: 'Wipe tables', frequency: 7, last_done: Date.today - 7})
Chore.create({title: 'Dust living area', frequency: 14, last_done: Date.today - 7})
Chore.create({title: 'Sweep balcony', frequency: 30, last_done: Date.today - 7})
Chore.create({title: 'Dust bedside tables', frequency: 7, last_done: Date.today - 7})
Chore.create({title: 'Dust spare rooms', frequency: 14, last_done: Date.today - 7})
Chore.create({title: 'Scrub shower', frequency: 14, last_done: Date.today - 7})
Chore.create({title: 'Toilet', frequency: 7, last_done: Date.today - 7})
Chore.create({title: 'Bathroom surfaces', frequency: 7, last_done: Date.today - 7})